## Introdução ao Framework PyTorch

A computação em modelos de Deep Learning é feita com tensores, que são generalizações de uma matriz que pode ser indexada em mais de duas dimensões. O PyTorch é um framework que aplica operações matemáticas a tensores para então treinar modelos de Deep Learning.

**TorchScript**

O PyTorch TorchScript ajuda a criar modelos serializáveis e otimizáveis. Depois que treinamos esses modelos, eles também podem ser executados independentemente. Isso ajuda quando estamos no estágio de implantação do modelo de um projeto de Data Science.

Você pode treinar um modelo no PyTorch usando Python e depois exportá-lo via TorchScript para um ambiente de produção em que Python não esteja disponível. 

**Treinamento Distribuído**

O PyTorch também oferece suporte a treinamento distribuído que permite que pesquisadores e profissionais paralelizem seus cálculos. O treinamento distribuído possibilita o uso de várias GPUs para processar lotes maiores de dados de entrada. Isso, por sua vez, reduz o tempo de computação.

**Suporte para Python**

O PyTorch tem uma interação muito boa com o Python. De fato, a codificação no PyTorch é bastante semelhante ao que fazemos em Python. Portanto, se você se sentir confortável com o Python, vai adorar trabalhar com o PyTorch.

In [2]:
# Instalando o PyTorch

!pip install -q -U torch torchvision


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# Imports 
import numpy as np
import torch
import torchvision

# <font color = "red"> Criando e Manipulando Tensores

A razão pela qual usamos o Numpy em Machine Learning é que é muito mais rápido do que as listas Python na execução de operações de matriz. 

Por quê? Internamente, NumPy faz a maior parte do trabalho pesado em Linguagem C, que é muito mais veloz que Python. 

Mas, no caso de treinar redes neurais profundas (<a href="http://www.deeplearningbook.com.br/">Deep Learning</a>), os arrays NumPy levariam meses para treinar algumas das redes de ponta. É aqui que os tensores entram em cena. O PyTorch nos fornece uma estrutura de dados chamada Tensor, que é muito semelhante à matriz ND do NumPy. Mas, diferentemente do último, os tensores podem aproveitar os recursos de uma GPU para acelerar significativamente as operações com matrizes.

In [4]:
# Criando um tensor

x = torch.tensor([1., 2.])

In [5]:
type(x)

torch.Tensor

In [6]:
print(x)

tensor([1., 2.])


In [7]:
# Criando um tensor
t = torch.tensor([[1,1,1,1],
                  [2,2,2,2],
                  [3,3,3,3]], dtype = torch.float32)

In [8]:
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [9]:
t.shape

torch.Size([3, 4])

Para determinar a forma desse tensor, examinamos primeiro as linhas (3) e depois as colunas (4). Portanto, esse tensor é 3 x 4 de classificação (rank) 2. 

Rank é uma palavra comumente usada e significa apenas o número de dimensões presentes no tensor.

No PyTorch, temos duas maneiras de obter a forma (shape):

In [10]:
t.size()

torch.Size([3, 4])

In [11]:
x.shape

torch.Size([2])

No PyTorch, o tamanho e a forma de um tensor significam a mesma coisa.

Normalmente, depois de conhecermos a forma de um tensor, podemos deduzir algumas coisas. Primeiro, podemos deduzir o rank do tensor. O rank de um tensor é igual ao comprimento da forma do tensor.

In [12]:
len(t.shape)

2

Também podemos deduzir o número de elementos contidos no tensor. O número de elementos dentro de um tensor (12 no nosso caso do tensor t e 2 no tensor x) é igual ao produto dos valores dos componentes da forma.

In [13]:
torch.tensor(t.shape).prod()

tensor(12)

In [14]:
torch.tensor(x.shape).prod()

tensor(2)

In [15]:
# Retornando um elemento de um tensor

z = torch.tensor([[1.,2.],
                  [5.,3.],
                  [0.,4.]])

In [16]:
z

tensor([[1., 2.],
        [5., 3.],
        [0., 4.]])

In [17]:
# Shape
z.shape

torch.Size([3, 2])

In [18]:
z[0][0]

tensor(1.)

In [19]:
z[0][0].item()

1.0

Quando criamos tensores randômicos

In [20]:
input1 = torch.randn([1,4,4,2]) # dimensões do tensor

In [21]:
input2 = torch.randn(1,4,4,2) # dimensões do tensor

In [22]:
input1.shape

torch.Size([1, 4, 4, 2])

In [23]:
input2.shape

torch.Size([1, 4, 4, 2])

In [24]:
input1

tensor([[[[ 1.2203,  0.5879],
          [ 0.5096,  0.9521],
          [ 0.7110,  0.1273],
          [ 0.5357, -0.1864]],

         [[ 1.0555, -1.0520],
          [-0.5798,  0.5294],
          [ 0.7682, -1.1244],
          [-0.4007, -1.3752]],

         [[ 0.1771,  0.1002],
          [-0.7342, -0.6756],
          [ 0.9680, -0.4251],
          [ 0.1707,  0.7173]],

         [[-1.1676,  0.8598],
          [-0.7218, -0.1816],
          [-0.4682, -0.2801],
          [ 0.1759, -0.2912]]]])

In [25]:
input2

tensor([[[[ 1.2916,  0.8772],
          [ 0.1565,  0.7790],
          [ 0.3530, -0.3958],
          [ 1.5127,  0.0281]],

         [[-0.5889, -0.4491],
          [ 1.6400, -0.3576],
          [ 0.7487,  1.0776],
          [ 1.2426,  0.8363]],

         [[ 0.9001,  1.9691],
          [ 1.0171, -0.7569],
          [-0.7837, -1.9109],
          [-0.6520, -0.1323]],

         [[-0.9059,  0.7521],
          [-0.3560,  0.7828],
          [ 0.3046, -1.1433],
          [ 0.7606,  1.4190]]]])

In [26]:
len(input1.shape) # RANK 4

4

Considere tensores como o número de listas que uma dimensão contém. Por exemplo, um tensor (1, 4, 4, 2) terá:

1 lista contendo 4 elementos de 4 elementos de 2 elementos.

- A primeira dimensão pode conter 1 elemento.
- A segunda dimensão pode conter 4 elementos.
- A terceira dimensão pode conter 4 elementos.
- A quarta dimensão pode conter 2 elementos.

###  <font color = "green">Array Numpy x Tensor PyTorch

In [27]:
# Criando array Numpy
a = np.array(1)

# Criando um tensor PyTorch
b = torch.tensor(1)

In [28]:
type(a)

numpy.ndarray

In [29]:
type(b)

torch.Tensor

In [30]:
print(a)
print(b)

1
tensor(1)


###  <font color = "green">Operações com Tensores

In [31]:
# Criando 2 tensores
t1 = torch.tensor(12)
t2 = torch.tensor(4)

print(t1,t2)

tensor(12) tensor(4)


In [32]:
# Operações
print(t1 + t2)
print(t1 - t2)
print(t1 * t2)
print(t1 / t2)

tensor(16)
tensor(8)
tensor(48)
tensor(3.)


###  <font color = "green">Operações com Matrizes

In [33]:
# Matriz (tensor rank 2) de números randomicos

t_rank2 = torch.randn(3,3)
t_rank2

tensor([[ 0.7124, -0.0788,  0.5999],
        [-0.4323, -1.6272, -1.5149],
        [ 1.2206, -0.2145, -0.7042]])

In [34]:
# Tensor (tensor rank 3) de números randomicos

t_rank3 = torch.randn(3,3,3)
t_rank3

tensor([[[ 1.5223,  0.8161,  0.7900],
         [ 0.3050,  0.5300, -1.0120],
         [ 0.4399,  0.4866,  0.5294]],

        [[-0.3552, -0.0850,  0.1343],
         [ 1.4736,  0.3980,  0.8333],
         [ 0.7913,  1.3257, -1.1465]],

        [[-0.3199, -1.8298, -0.8159],
         [ 1.0909, -0.0784, -1.0942],
         [ 0.9880, -0.2991, -1.4457]]])

In [35]:
# Tensor (tensor rank 4) de números randomicos

t_rank4 = torch.randn(3,3,3,3)
t_rank4

tensor([[[[ 0.7711, -1.3898, -0.2500],
          [-0.8478, -1.2022, -0.0053],
          [ 0.0486,  0.2441, -1.4416]],

         [[ 1.1281,  0.2417, -0.0394],
          [-1.2206,  0.9756,  1.4264],
          [-0.4642, -0.7695,  1.5576]],

         [[-0.4175, -0.7117,  0.2053],
          [ 0.2113, -0.0438,  0.2232],
          [ 0.3566,  0.1974,  1.0227]]],


        [[[-0.5355,  0.6644, -1.4372],
          [ 2.5216, -0.2925, -0.4249],
          [-0.5397, -1.7578,  0.8084]],

         [[ 0.0208, -0.5669,  0.3912],
          [ 0.2375,  0.8687,  0.7309],
          [-1.2892, -0.1461, -0.7296]],

         [[ 0.8267,  0.0766,  0.0308],
          [ 0.6296,  0.1954,  0.2968],
          [ 0.4078, -1.3901,  1.1360]]],


        [[[-0.2452,  0.2646, -1.1904],
          [ 1.0139,  1.3802, -1.2012],
          [ 0.1038, -1.8596, -0.4290]],

         [[-0.1290,  1.0075,  1.4208],
          [-0.6223,  0.2648, -1.4618],
          [-0.0382, -0.1587, -0.7667]],

         [[ 0.3754,  0.5690,  0.8524],
     

In [36]:
# Mutiplicação entre 2 tensores
A = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
B = torch.tensor([[9,8,7], [6,5,4], [3,2,1]])

In [37]:
A.shape

torch.Size([3, 3])

In [38]:
B.shape

torch.Size([3, 3])

In [39]:
len(A)

3

In [40]:
len(B)

3

In [41]:
resultado1 = A * B

In [42]:
resultado1

tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])

In [43]:
resultado2 = torch.matmul(A,B)

In [44]:
resultado2

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

In [45]:
resultado3 = torch.sum(A * B)

In [46]:
resultado3

tensor(165)

Para Multiplicação de matrizes, fazemos assim em PyTorch:

In [51]:
AB1 = A.mm(B)
# Ou
AB2 = torch.mm(A, B)
# OU
AB3 = torch.matmul(A, B) 
# OU
AB4 = A @ B

In [52]:
print(AB1, AB2, AB3, AB4)

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]]) tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]]) tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]]) tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])


In [53]:
## Essa notação abaixo realiza a multiplicação element-wise:
A * B

tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])

In [54]:
# Usando seed para iniciar 2 tensores com valores randomicos
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)

In [55]:
# Adição de Matrizes
torch.add(a,b)

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])

In [56]:
# Subtração de Matrizes
torch.sub(a,b)

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])

In [57]:
# Multiplicação 
torch.mm(a,b)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [58]:
# Divisão Matrizes
torch.div(a, b)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])

In [59]:
# Matriz original
print(a, "\n")

# Matriz transposta
print(torch.t(a))

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 

tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])
