In [1]:
from platform import python_version

In [3]:
python_version()

'3.9.13'

In [4]:
import numpy as np

In [14]:
# Estrutura de dados

In [15]:
array1 = np.array([10,20,30,40])

In [16]:
array1.shape

(4,)

In [17]:
array1.ndim

1

In [18]:
array2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [19]:
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
array2.shape

(2, 5)

# Python TUDO É OBJETO

In [21]:
# Método
array2.max()

10

In [22]:
#atributo
array2.ndim

2

### Criando estrutura com arange

In [29]:
array3 = np.arange(15)

In [30]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
# Utilizando start/end
array4 = np.arange(0,15,3)

In [32]:
array4

array([ 0,  3,  6,  9, 12])

### Criando estrutura com linspace

In [37]:
# 9start, end, nº de elementos)
array5 = np.linspace(0,3,4); array5

array([0., 1., 2., 3.])

In [38]:
# np.zeros
array6 = np.zeros((10,5)); array6

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
# np.ones
array7 = np.ones((2,3,2)); array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [44]:
array7.ndim

3

In [51]:
# np.eye MATRIZ DIAGONAL
array8 = np.eye(8); array8

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [52]:
# np.diag
array9 = np.diag((2,1,4,6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])