In [2]:
from platform import python_version

In [3]:
python_version()

'3.9.13'

In [4]:
import numpy as np

In [5]:
# Estrutura de dados

In [6]:
array1 = np.array([10,20,30,40])

In [7]:
array1.shape

(4,)

In [8]:
array1.ndim

1

In [9]:
array2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [10]:
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
array2.shape

(2, 5)

# Python TUDO É OBJETO

In [12]:
# Método
array2.max()

10

In [13]:
#atributo
array2.ndim

2

### Criando estrutura com arange

In [14]:
array3 = np.arange(15)

In [15]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
# Utilizando start/end
array4 = np.arange(0,15,3)

In [17]:
array4

array([ 0,  3,  6,  9, 12])

### Criando estrutura com linspace

In [18]:
# 9start, end, nº de elementos)
array5 = np.linspace(0,3,4); array5

array([0., 1., 2., 3.])

In [19]:
# np.zeros
array6 = np.zeros((10,5)); array6

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
# np.ones
array7 = np.ones((2,3,2)); array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
array7.ndim

3

In [22]:
# np.eye MATRIZ DIAGONAL
array8 = np.eye(8); array8

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
# np.diag
array9 = np.diag((2,1,4,6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

### numpy.random.rand

In [35]:
np.random.seed(100) # set seed
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [36]:
# Ditribuição normal - gausaian
array11 = np.random.randn(3); array11

array([ 0.35467445, -0.78606433, -0.2318722 ])

### numpy.empty

In [38]:
array12 = np.empty((3,2)); array12

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 2.22522053e-306],
       [1.89146896e-307, 7.56571288e-307]])

### numpy.tile

In [39]:
np.array([[9,4], [3,7]])

array([[9, 4],
       [3, 7]])

In [41]:
np.tile(np.array([[9,4], [3,7]]),5)

array([[9, 4, 9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7, 3, 7]])

In [42]:
np.tile(np.array([[9,4], [3,7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

# Tipos de dados Numpy

In [43]:
array13 = np.array([8, -3, 5, 9], dtype='float')

In [44]:
print(array13)

[ 8. -3.  5.  9.]


In [45]:
array13.dtype

dtype('float64')

In [48]:
array14 = np.array([5,9,8,2,6])

In [49]:
array14.dtype

dtype('int32')

In [52]:
array15 = np.array([2.,6,9,8]); array15.dtype

dtype('float64')

In [54]:
array16 = np.array(['Alysson', 'Melo', 'popo']); array16.dtype

dtype('<U7')

In [55]:
array17 = np.array([True, False, True]); array17.dtype

dtype('bool')

In [58]:
array18 = np.array([50, -69, 17.47])

In [59]:
# Conversão de tipos
array18.astype(int)

array([ 50, -69,  17])

# Operações com Arrays

In [60]:
array19 = np.arange(0,30) * 5; print(array19)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145]


In [62]:
array20 = np.arange(5) ** 4; print(array20)

[  0   1  16  81 256]


In [63]:
array21 = np.arange(0, 30) + 1; print(array21)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [64]:
array22 = np.arange(0,30,3) + 3
array23 = np.arange(1,11)

In [65]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [66]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
# Subtração

array22 -array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [68]:
# Soma

array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [69]:
# Comparação 

array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [72]:
arr1 = np.array([True, False, True, False])
arr2 = np.array([False, False, True, False])
np.logical_and(arr1, arr2)

array([False, False,  True, False])