In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5])

In [3]:
print(array1)

[1 2 3 4 5]


In [5]:
print(array1[-1])

5


In [6]:
# Invertendo o array
array1[::-1]

array([5, 4, 3, 2, 1])

### Slicing de arrays multidimensionais

In [7]:
array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(array3[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [13]:
# Atribuição 
array3[1,1] = 12312; print(array3)

[[    1     2     3]
 [    4 12312     6]
 [    7     8     9]]


### Slicing de Array

In [16]:
array5 = np.arange(50)*2 ; print(array5)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [17]:
array5[8:30:2]

array([16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56])

In [20]:
array5[20:]

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72,
       74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [22]:
array5[::3]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [23]:
#Slicing não altera objeto original
array5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [24]:
#Atribuição com slicing
array5[:4] = 1; array5

array([ 1,  1,  1,  1,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [28]:
array5[:8] = np.zeros(8); array5

array([ 0,  0,  0,  0,  0,  0,  0,  0, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [31]:
### Subset de Arrays
array8 = array5[::8] ; print(array8)

[ 0 16 32 48 64 80 96]


## Cópias de Arrays com np.copy

In [33]:
array9 = np.arange(8) ; print(array9)

[0 1 2 3 4 5 6 7]


In [34]:
array10 = array9.copy(); array10

array([0, 1, 2, 3, 4, 5, 6, 7])