In [1]:
import numpy as np

## Transposição e Reshaping de Arrays

In [2]:
array1 = np.array([[65,23,19], [41,87,10]])

In [3]:
array1

array([[65, 23, 19],
       [41, 87, 10]])

In [6]:
print(array1.T) # Transposição de Arrays - invertendo a ordem

[[65 41]
 [23 87]
 [19 10]]


In [8]:
print(np.transpose(array1))

[[65 41]
 [23 87]
 [19 10]]


## Broadcasting 